services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: grafana_new
      POSTGRES_PASSWORD: grafana123
      POSTGRES_DB: my_dashboard_rutf8
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./grafanafromwin.sql:/grafwin.sql
    ports:
      - "5433:5432"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - PUID=1000
      - GUID=1000
    ports:
      - "4000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - postgres
